default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: amorittabox

development:
  <<: *default
  database: amorittabox_development
  password: <%= ENV['AMORITTABOX_DEVELOPMENT_DATABASE_PASSWORD'] %>
test:
  <<: *default
  database: amorittabox_test
  password: <%= ENV['AMORITTABOX_TEST_DATABASE_PASSWORD'] %>
production:
  <<: *default
  database: amorittabox_production
  password: <%= ENV['AMORITTABOX_PRODUCTION_DATABASE_PASSWORD'] %>
